# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r:
- oldrel
- release
- devel

addons:
    apt:
        packages:
            - libgsl0-dev
            - libmagick++-dev

before_cache:
  - R CMD INSTALL *.tar.gz
  - Rscript -e 'remotes::install_cran("pkgdown"); pkgdown::build_site(override = list(development = "auto"))'

deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  local_dir: docs
  skip_cleanup: true
  on:
      branch: master
      condition: $TRAVIS_R_VERSION_STRING == "release"
