name: pkgdown

on:
  push:
    branches: master

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v1
      with:
        r-version: 4.x
        Ncpus: 2
    - uses: r-lib/actions/setup-pandoc@master
    - name: Install dependencies
      run: |
        Rscript -e 'install.packages("remotes")' \
                -e 'remotes::install_deps(dependencies = TRUE)' \
                -e 'remotes::install_github("jimhester/pkgdown@github-actions-deploy")'
    - name: Install package
      run: R CMD INSTALL .
    - name: Deploy package
      run: |
        Rscript -e "pkgdown:::deploy_local(new_process = FALSE, remote_url = 'https://x-access-token:${{ secrets.PACKAGE_ACCESS_TOKEN }}@github.com/${{ github.repository }}.git')"
