name: R package CI

on: [push]

jobs:
  build:
    container:
      image: rocker/verse:latest
      volumes:
        - my_docker_volume:/volume_mount
    steps:
    - name: Dump runner context
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: echo "$RUNNER_CONTEXT"
    - uses: actions/checkout@v1
    - name: R checks
      run: |
        cd r
        Rscript -e 'remotes::install_deps(dependencies = TRUE)'
        R CMD build
        R CMD check --as-cran
