name: R package CI

on: [push]

jobs:
  build:
    container:
      image: rocker/verse:latest
      volumes: $PWD/r
    steps:
    - uses: actions/checkout@v1
    - name: R checks
      run: |
        cd r
        Rscript -e 'remotes::install_deps(dependencies = TRUE)'
        R CMD build
        R CMD check --as-cran
