name: R package CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rocker/verse:latest
    steps:
    - uses: actions/checkout@v1
    - name: Install apt dependencies
      run: apt update && apt install libgsl-dev
    - name: Install dependencies
      run: |
        Rscript -e '
        deps <- remotes::dev_package_deps(dependencies = NA);
        remotes::install_deps(dependencies = TRUE);
        if (!all(deps$package %in% installed.packages())) {
          message("missing: ", paste(setdiff(deps$package, installed.packages()), collapse=", "));
          q(status = 1, save = "no")
        }'
    - name: Build package
      run: R CMD build
    - name: Check package
      run: R CMD check --as-cran *.tar.gz
