name: R package CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: R checks
      run: docker run -v $PWD:/r rocker/verse:latest /bin/bash -c "cd r && Rscript -e 'remotes::install_deps(dependencies = TRUE)' && R CMD build && R CMD check --as-cran"
