name: R package CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Clone repository
      run: docker run rocker/verse:latest git clone https://github.com/$GITHUB_REPOSITORY
    - name: Checkout commit
      run: docker run rocker/verse:latest git checkout $GITHUB_SHA
    - name: Install dependencies
      run: docker run rocker/verse:latest Rscript -e 'remotes::install_deps(dependencies = TRUE)'
    - name: Build package
      run: docker run rocker/verse:latest R CMD build
    - name: Check package
      run: docker run rocker/verse:latest R CMD check --as-cran
