name: R package CI

on: [push, pull_request]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - uses: r-lib/actions/setup-r@v1
    - name: Install dependencies
      run: Rscript -e "install.packages(c('pkgdown', 'remotes', 'rcmdcheck'))" -e "remotes::install_deps(dependencies = TRUE)"
    - name: Check
      run: Rscript -e "rcmdcheck::rcmdcheck(args = '--no-manual', error_on = 'error')"
    - name: Install packages
      run: R CMD INSTALL .
    - name: Build pkgdown site
      run: Rscript -e 'pkgdown::build_site()'
    - name: Deploy pkgdown site
      if: success() && github.ref == 'refs/heads/master' && runner.os == 'macOS'
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
          GITHUB_TOKEN: ${{ secrets.PACKAGE_ACCESS_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: docs
