name: R package CI

on: [push, pull_request]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - uses: r-lib/actions/setup-r@v1
    - name: Install dependencies
      run: Rscript -e "install.packages(c('pkgdown', 'remotes', 'rcmdcheck'))" -e "remotes::install_deps(dependencies = TRUE)"
    - name: Check
      run: Rscript -e "rcmdcheck::rcmdcheck(args = '--no-manual', error_on = 'error')"
    - name: Install packages
      run: R CMD INSTALL .
    - name: Deploy pkgdown site
      if: success() && github.ref == 'refs/heads/master' && runner.os == 'macOS'
      run: Rscript -e "pkgdown:::deploy_local(new_process = FALSE, remote_url = 'https://x-access-token:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git')"
